codes:
  - spiffe:
      settings:
          define_geometry.zmin: -0.001
          define_geometry.nz: 515
      parameters:
      setup:
        input_file: gun.spiffe
        execution_type: serial
options:
  software: mesh_scan
  sym_links:
    - dc.geo